@startuml
class Animation {
    {field} fps
    {field} current_frame
    {method} update()
    {method} draw()
    {method} get_current_frame()
    {method} next_frame()
}

class Frame {
    {field} width
    {field} height
    {field} bgcolor
    {method} get_image()
    {method} draw()
}

class Brush {
    {field} size
    {field} color
    {method} press()
    {method} move()
}

Animation -* Frame
Brush -- Frame : draw on >
@enduml