@startuml
class Animation {
    {field} fps
}

class Frame {
    {field} bgcolor
}

class Action

class Stroke {
    {field} array
}

class BrushStroke {
    {field} color
}

class EraserStroke

Animation -* Frame
Frame -* Action
Action <- Stroke
Stroke <- BrushStroke
Stroke <- EraserStroke
@enduml